t_data_source = "/Users/arunshriram/Documents/SLAC Internship/MONster/test"
s_data_source = "None"
i_data_source = "/Users/arunshriram/Documents/SLAC Internship/MONster/test"
t_calib_source = "/Users/arunshriram/Documents/SLAC Internship/MONster/calib/cal_28mar18.calib"
i_calib_source = "/Users/arunshriram/Documents/SLAC Internship/MONster/calib/cal_28mar18.calib"
t_processed_loc = "/Users/arunshriram/Documents/SLAC Internship/MONster/test"
s_processed_loc = "/Users/arunshriram/Documents/SLAC Internship/MONster/StitchedImgs_all"
i_processed_loc = "/Users/arunshriram/Documents/SLAC Internship/MONster/test"
two_d_image = "/Users/arunshriram/Documents/SLAC Internship/MONster/test/Processed/k5_022318_1_24x24_t45_0313_gamma.png"
stitch_image = "/Users/arunshriram/Documents/SLAC Internship/MONster/StitchedImgs_all/b_mehta_IR66BE_th0p2_scan_gamma"
one_d_image = "/Users/arunshriram/Documents/SLAC Internship/MONster/test/Processed/k5_022318_1_24x24_t45_0314_1D.png"
qmin = "1.0"
qmax = "6.0"
chimin = "-20.0"
chimax = "20.0"
findex = "1"
lindex = "9"

